analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - 'analysis_options.yaml'
    - '.dart_tool/**'
    - 'build/**'
    - 'coverage/**'
    - 'android/**'
    - 'web/**'
    - 'windows/**'
    - '.packages'
    - '.flutter-plugins'
    - '.flutter-plugins-dependencies'
    - 'lib/generated_plugin_registrant.dart'
    - '**/*.freezed.dart'
    - '**/*.g.dart'

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 10000
    number-of-parameters: 10000
    maximum-nesting-level: 10000
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
  anti-patterns:
    - long-method
    - long-parameter-list
